##  Part A- Notebook to demonstrate NumPy Operations

##  1. An array that starts from the integer 1, ends at 20, incremented by 3.

In [119]:
import numpy as np

# array starting from 1, ending at 20, incremented by 3
my_array = np.arange(1, 21, 3)

print(my_array) 

[ 1  4  7 10 13 16 19]


## 2. Create a new array of shape 3 with random numbers between 0 and 1.

In [120]:

# array of shape 3 with random numbers between 0 and 1
random_array = np.random.rand(3)

print(random_array)

[0.84479385 0.80432798 0.84834979]


## 3. A 2 D array [[10,20,45],[30,12,16],[42,17,56]] and perform the following operations:
      Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.

In [121]:

# Create a 2D array
my_2d_array = np.array([[10, 20, 45],
                        [30, 12, 16],
                        [42, 17, 56]])

# Slice to get the first two rows
first_two_rows = my_2d_array[:2, :]

# Slice to get the last two rows
last_two_rows = my_2d_array[1:, :]

# Print the results
print("Original 2D array:")
print(my_2d_array)

print("\nSliced array - First two rows:")
print(first_two_rows)

print("\nSliced array - Last two rows:")
print(last_two_rows)

Original 2D array:
[[10 20 45]
 [30 12 16]
 [42 17 56]]

Sliced array - First two rows:
[[10 20 45]
 [30 12 16]]

Sliced array - Last two rows:
[[30 12 16]
 [42 17 56]]


## 4. Two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.

In [122]:

# Create two 2x2 arrays
array1 = np.array([[1, 2], 
                   [3, 4]])

array2 = np.array([[5, 6], 
                   [7, 8]])

print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

# Vertically stack the arrays
vertical_stack = np.vstack((array1, array2))

print("\nVertically Stacked:")
print(vertical_stack)


# Horizontally stack the arrays
horizontal_stack = np.hstack((array1, array2))

print("\nHorizontally Stacked:")
print(horizontal_stack)

# vertically stacked array into two smaller arrays
split_vertical = np.vsplit(vertical_stack, 2)

print("\nSplit Vertically:")
for arr in split_vertical:
    print(arr)

#  horizontally stacked array into two smaller arrays
split_horizontal = np.hsplit(horizontal_stack, 2)

print("\nSplit Horizontally:")
for arr in split_horizontal:
    print(arr)

Array 1:
[[1 2]
 [3 4]]

Array 2:
[[5 6]
 [7 8]]

Vertically Stacked:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontally Stacked:
[[1 2 5 6]
 [3 4 7 8]]

Split Vertically:
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]

Split Horizontally:
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


## 5. Create two matrices 𝑋= ([[5,7,2],[4,5,6],[7,4 ,2]]),𝑌= ([[4,2],[6,2],[4,2]]),
    Is it possible to multiply these matrices?
    Demonstrate the case when it is not possible to.

In [123]:
# Create matrices X and Y
X = np.array([[5, 7, 2], 
              [4, 5, 6],
              [7, 4, 2]])

Y = np.array([[4, 2], 
              [6, 2], 
              [4, 2]])

# Check if matrix multiplication is possible
if X.shape[1] == Y.shape[0]:

    # Perform matrix multiplication
    result = np.dot(X, Y)

    print("Matrix Multiplication Result:")
    print(result)
else:
    print("Matrix multiplication is not possible due to incompatible dimensions.")


Matrix Multiplication Result:
[[70 28]
 [70 30]
 [60 26]]


## 6.  Create two arrays, 𝑥 = ([2,−1,−8]) 𝑦 = ([3,1,−2]),
     Find the Shape, Number of dimensions of vector x.
     Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).

In [124]:
# Create arrays x and y
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

# Find the shape and number of dimensions of vector x
shape_x = x.shape
dimensions_x = x.ndim

print("Vector x:")
print("Shape:", shape_x)
print("Number of dimensions:", dimensions_x)

# Reshape vector x to a matrix of size (3,1)
x_reshaped = x.reshape((3, 1))

# Reshape vector y to a matrix of size (3,1)
y_reshaped = y.reshape((3, 1))

# Determine the number of dimensions after reshaping y
dimensions_y_reshaped = y_reshaped.ndim

print("\nReshaped matrix x:")
print(x_reshaped)
print("Number of dimensions after reshaping x:", x_reshaped.ndim)

print("\nReshaped matrix y:")
print(y_reshaped)
print("Number of dimensions after reshaping y:", dimensions_y_reshaped)


Vector x:
Shape: (3,)
Number of dimensions: 1

Reshaped matrix x:
[[ 2]
 [-1]
 [-8]]
Number of dimensions after reshaping x: 2

Reshaped matrix y:
[[ 3]
 [ 1]
 [-2]]
Number of dimensions after reshaping y: 2


## 7. How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.

In [125]:
# Create a 3x3 matrix
matrix = np.array([[9, 8, 7],
                   [6, 5, 4],
                   [3, 2, 1]])



# Print the results
print("Original Matrix:")
print(matrix)

# Define a vector for subtraction and multiplication
subtraction_vector = np.array([9, 8, 7])
multiplication_scalar = 4

# Broadcasting for subtraction
result_subtraction = matrix - subtraction_vector

print("\nSubtracting Vector (Broadcasting):")
print(result_subtraction)

# Broadcasting for multiplication
result_multiplication = matrix * multiplication_scalar

print("\nMultiplying by Scalar (Broadcasting):")
print(result_multiplication)


Original Matrix:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Subtracting Vector (Broadcasting):
[[ 0  0  0]
 [-3 -3 -3]
 [-6 -6 -6]]

Multiplying by Scalar (Broadcasting):
[[36 32 28]
 [24 20 16]
 [12  8  4]]


## Part B- Linear Equations
   Determine the singularity of the system of equations, comment on the expected solution of the system. Solve the system of equations if 
   possible. Justify the reason why you believe the system can or cannot be solved using NumPy functions.

## Part B.1  
 
   1. 4x + y - 2z = 10
   2. 2x - 3y + 2z = -4
   3. x + 2y + 3z = 6

In [126]:
# Coefficient matrix A
A = np.array([[4, 1, -2],
              [2, -3, 2],
              [1, 2, 3]])


# Calculate determinant of A
det_A = np.linalg.det(A)

print("Determinant of Matrix A:", det_A)


# Right-hand side vector B
B = np.array([10, -4, 6])

# Solve the system of equations if it is non-singular
if det_A != 0:
    solution = np.linalg.solve(A, B)
    print("Solution for the system:")
    print(solution)
else:
    print("The system is singular, and a unique solution may not exist.")





Determinant of Matrix A: -70.00000000000003
Solution for the system:
[ 1.8  2.4 -0.2]


## Part B.2
   1. 2x - y + 3z + 4w = 10
   2. 4x - 2y + 6z + 8w = 20
   3. 3x + y - 2z + 2w = 3
   4. x + 3y - 4z + w = -1

In [127]:
# Coefficient matrix A
A = np.array([[2, -1, 3, 4],
              [4, -2, 6, 8],
              [3, 1, -2, 2],
              [1, 3, -4, 1]])

# Calculate determinant of A
det_A = np.linalg.det(A)

# Check singularity and comment on the expected solution
if det_A != 0:
    print("The system is non-singular. It is expected to have a unique solution.")
else:
    print("The system is singular. It may have no solution or infinitely many solutions.")


# Right-hand side vector B
B = np.array([10, 20, 3, -1])

# Solve the system of equations if it is non-singular
if det_A != 0:
    solution = np.linalg.solve(A, B)
    print("\nSolution for the system:")
    print(solution)
else:
    print("\nThe system is singular, and a unique solution may not exist.")



The system is singular. It may have no solution or infinitely many solutions.

The system is singular, and a unique solution may not exist.
